wtq_template = '\nYou are an expert table question-answering assistant. Your task is to analyze the provided Markdown table and the user\'s question, then generate a structured JSON response.\n\n**Instructions:**\n1.  **Analyze the Question:** Carefully understand what information the user is asking for from the table.\n2.  **Extract the Answer:** Locate the precise information in the table that directly answers the question.\n3.  **Formulate the Explanation:** Briefly describe, in a single sentence, the steps you took to find the answer in the table.\n4.  **Construct the JSON Output:** Create a single, valid JSON object with the following two keys:\n    - `"answer"`: A list of strings containing only the direct answer(s).\n    - `"explanation"`: A string containing your concise, one-sentence explanation.\n\n**Important:** Your final output must **only** be the JSON object. Do not include any text before or after the JSON.\n\n**Table:**\n```\n{md_table}\n```\n\n**Question:**\n{question}\n\n**JSON Answer:**\n'.lstrip()
tabfact_template = '\nYou are an expert table fact verification assistant. Your task is to analyze the provided Markdown table and the given statement, then generate a structured JSON response to determine if the statement is factually supported by the table.\n\n**Instructions:**\n1.  **Analyze the Statement:** Carefully understand what claim is being made in the given statement.\n2.  **Examine the Table:** Search through the table data to find evidence that either supports or contradicts the statement.\n3.  **Make the Determination:** Decide whether the statement is **True** (supported by the table) or **False** (contradicted by the table).\n4.  **Formulate the Explanation:** Briefly describe, in a single sentence, the evidence you found in the table that supports your decision.\n5.  **Construct the JSON Output:** Create a single, valid JSON object with the following two keys:\n    - `"answer"`: A list containing exactly one string, either ["True"] or ["False"].\n    - `"explanation"`: A string containing your concise, one-sentence explanation.\n\n**Important:** Your final output must **only** be the JSON object. Do not include any text before or after the JSON.\n\n**Table:**\n```\n{md_table}\n```\n\n**Statement:**\n{question}\n\n**JSON Answer:**\n'.lstrip()
fetaqa_template = "\nQuestion: {question}\nProvide a direct, concise answer:\n"
tabmwp_template = '\nYou are an expert table question-answering assistant specializing in mathematical reasoning. Your task is to analyze the provided Markdown table and the user\'s math problem, then generate a structured JSON response.\n\n**Instructions:**\n1.  **Analyze the Math Problem:** Carefully understand what mathematical operation or reasoning is required from the table data.\n2.  **Perform the Calculation:** Execute the necessary mathematical operations (arithmetic, statistics, comparisons, etc.) using the table data.\n3.  **Extract the Answer:** Determine the precise numerical result or text answer that solves the math problem.\n4.  **Formulate the Explanation:** Briefly describe, in a single sentence, the mathematical steps you took to solve the problem.\n5.  **Construct the JSON Output:** Create a single, valid JSON object with the following two keys:\n    - `"answer"`: A list of strings containing only the direct answer(s).\n    - `"explanation"`: A string containing your concise, one-sentence explanation.\n\n**Important:** Your final output must **only** be the JSON object. Do not include any text before or after the JSON.\n\n**Table:**\n```\n{md_table}\n```\n\n**Math Problem:**\n{question}\n\n**JSON Answer:**\n'.lstrip()
hitab_template = '\nYou are an expert table question-answering assistant specializing in hierarchical tables. Your task is to analyze the provided complex Markdown table and the user\'s question, then generate a structured JSON response.\n\n**Table Structure Notes:**\n- This table may have hierarchical headers (multiple header rows)\n- Some cells may be merged or span multiple rows/columns\n- Column headers may be nested or grouped\n- Pay attention to the table structure to understand data relationships\n\n**Instructions:**\n1.  **Analyze the Table Structure:** First understand the hierarchical organization of headers and how data is grouped\n2.  **Analyze the Question:** Carefully understand what information the user is asking for from the table\n3.  **Navigate the Table:** Use the hierarchical headers to locate the correct data section\n4.  **Extract the Answer:** Locate the precise information in the table that directly answers the question\n5.  **Formulate the Explanation:** Briefly describe, in a single sentence, the steps you took to find the answer in the hierarchical table structure\n6.  **Construct the JSON Output:** Create a single, valid JSON object with the following two keys:\n    - `"answer"`: A list of strings containing only the direct answer(s).\n    - `"explanation"`: A string containing your concise, one-sentence explanation.\n\n**Important:** Your final output must **only** be the JSON object. Do not include any text before or after the JSON.\n\n**Table:**\n```\n{md_table}\n```\n\n**Question:**\n{question}\n\n**JSON Answer:**\n'
infotabs_template = '\nYou are an expert table fact verification assistant. Your task is to analyze the provided Markdown table and the given hypothesis, then generate a structured JSON response to determine the logical relationship between the hypothesis and the table.\n\n**Instructions:**\n1.  **Analyze the Hypothesis:** Carefully understand what claim is being made in the given hypothesis.\n2.  **Examine the Table:** Search through the table data to find evidence that either supports, contradicts, or is unrelated to the hypothesis.\n3.  **Make the Determination:** Decide whether the hypothesis is:\n    - **Entail**: The hypothesis is logically supported by the table data\n    - **Contradict**: The hypothesis is logically contradicted by the table data  \n    - **Neutral**: The table data is insufficient to determine the truth of the hypothesis\n4.  **Formulate the Explanation:** Briefly describe, in a single sentence, the evidence you found in the table that supports your decision.\n5.  **Construct the JSON Output:** Create a single, valid JSON object with the following two keys:\n    - `"answer"`: A list containing exactly one string, either ["Entail"], ["Contradict"], or ["Neutral"].\n    - `"explanation"`: A string containing your concise, one-sentence explanation.\n\n**Important:** Your final output must **only** be the JSON object. Do not include any text before or after the JSON.\n\n**Table:**\n```\n{md_table}\n```\n\n**Hypothesis:**\n{question}\n\n**JSON Answer:**\n'.lstrip()
tatqa_template = '\nYou are an expert table question-answering assistant specializing in mathematical reasoning. Your task is to analyze the provided Markdown table and the user\'s question, then generate a structured JSON response.\n\n**Instructions:**\n1.  **Analyze the Question:** Carefully understand what mathematical operation or reasoning is required from the table data.\n2.  **Perform the Calculation:** Execute the necessary mathematical operations (arithmetic, statistics, percentage calculations, comparisons, etc.) using the table data.\n3.  **Extract the Answer:** Determine the precise numerical result or text answer that solves the question.\n4.  **Formulate the Explanation:** Briefly describe, in a single sentence, the mathematical steps you took to solve the problem.\n5.  **Construct the JSON Output:** Create a single, valid JSON object with the following two keys:\n    - `"answer"`: A list of strings containing only the direct answer(s).\n    - `"explanation"`: A string containing your concise, one-sentence explanation.\n\n**Important:** Your final output must **only** be the JSON object. Do not include any text before or after the JSON.\n\n**Table:**\n```\n{md_table}\n```\n\n**Question:**\n{question}\n\n**JSON Answer:**\n'.lstrip()
default_template = "\nGiven the table above and the question: {question}\nProvide only the direct answer.\n"
markdown_template_mapping = {
    "WTQ_for_TQA": wtq_template,
    "TABMWP_for_TQA": tabmwp_template,
    "TAT-QA_for_TQA": tatqa_template,
    "HiTab_for_TQA": hitab_template,
    "FeTaQA_for_TQA": fetaqa_template,
    "InfoTabs_for_TFV": infotabs_template,
    "TabFact_for_TFV": tabfact_template,
}
DEFAULT_MARKDOWN_PROMPT_BODY = "\nGiven the table above and the question: {question}\nProvide only the direct answer.\n"
